### ISSUE TITLE
Endpoint name is "main"

### ISSUE THREAD

**Issue by Nama** [AlpacaFur/Artemis.BDDiscord#1]
Hi,

mind changing the endpoint name to something discord related?
So tools searching for the endpoint can't fail if something else is called main, too.

https://github.com/AlpacaFur/Artemis.BDDiscord/blob/f2ecb83a1a571c9fb9ed77abe07b35a645804f48/Artemis.BDDiscord/BDDiscordModelExpansion.cs#L19

![grafik](https://user-images.githubusercontent.com/2297270/113767848-72c18e80-971f-11eb-86d3-3f13dc5bfff5.png)

**Comment by AlpacaFur** [comment]
Thanks for the suggestion! I just changed it to `betterDiscordData` and will post the new release shortly. This will require you to replace the plugin in BD as well as in Artemis.
